name: Bug
description: Something isn't working
labels: ["bug"]
body:
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected vs Actual Behavior
    validations:
      required: true
