name: Feature
description: New feature or enhancement
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What needs to be implemented?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: "- [ ] ..."
    validations:
      required: true
